name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Installing system requirements
        run: |
          pip install playwright[full]
          export PATH=$PATH:~/.local/bin/


      - name: Check if theHub.db exists
        run: |
          if [ ! -f "theHub.db" ]; then
            touch theHub.db
          fi

      - name: Run Python script
        run: python update-database.py

      - name: Commit changes
        run: |
          git config --local user.email "trinekaka@gmail.com"
          git config --local user.name "GitHub Action"
          git add theHub.db
          git commit -m "Update theHub.db [skip ci]"
