name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Installing system requirements
        run: |
          pip install playwright[full]
          export PATH=$PATH:~/.local/bin/
    
      - name: Connect to SQLite3 Database
        run: |
          python3 - <<EOF
          import sqlite3

          # Connect to the database
          conn = sqlite3.connect('theHub.db')
          conn.close()
          shell: bash
